"""Article-facing API for rare permutation p-value estimation."""

from jasa_mcmcis.beta import (
    estimate_scale_T,
    iid_pilot_statistics,
    init_beta_from_iid_pilot,
    q_target_from_gamma,
)
from jasa_mcmcis.exact import ExactPValueResult, LinearStatisticDPSolver
from jasa_mcmcis.grid import (
    BASE_SEED,
    BETA_INIT_PILOT_SAMPLES,
    BURN_IN_FRACTION,
    CHECKPOINTS,
    CONVERGENCE_TOLERANCE,
    GAMMAS,
    MCMC_CHAINS,
    MCMC_ESTIMATE_VARIANCE,
    MCMC_IS_BETA_PILOT_SEED_OFFSET,
    MCMC_IS_CHAIN_SEED_OFFSET,
    MCMCIS_SWAP_FRACTIONS,
    METHOD_BLOCKS,
    N_BINS,
    SAMC_CHAIN_SEED_OFFSET,
    SAMC_LAMBDA_MIN_PILOT,
    SAMC_SETUP_SEED_OFFSET,
    SAMC_SWAP_FRACTIONS,
    T0,
    TILT_MODE,
    job_seed,
    mcmc_is_chain_checkpoints,
    method_block_index,
    samc_chain_checkpoints,
)
from jasa_mcmcis.mcmcis import (
    MCMCISResult,
    hard_step_beta_for_target_tail_mass,
    hard_step_r_for_target_tail_mass,
    run_hard_step_mcmc_is,
    run_mcmc_is,
    run_mcmc_is_checkpoints,
)
from jasa_mcmcis.problem import FixedGroupConstraint, PermutationTestProblem
from jasa_mcmcis.samc import SAMCResult, estimate_lambda_min, run_samc, run_samc_checkpoints
from jasa_mcmcis.scenarios import (
    CROSS_METHOD_SCENARIO_KEYS,
    GWAS_NEAR_THRESHOLD_SCENARIO_KEYS,
    HEP_NEAR_THRESHOLD_SCENARIO_KEYS,
    NEAR_THRESHOLD_SCENARIO_KEYS,
    Scenario,
    available_scenarios,
    load_scenario,
    load_scenarios,
)
from jasa_mcmcis.statistics import difference_in_means, treated_sum

__all__ = [
    "BASE_SEED",
    "BETA_INIT_PILOT_SAMPLES",
    "BURN_IN_FRACTION",
    "CHECKPOINTS",
    "CONVERGENCE_TOLERANCE",
    "CROSS_METHOD_SCENARIO_KEYS",
    "ExactPValueResult",
    "FixedGroupConstraint",
    "GAMMAS",
    "GWAS_NEAR_THRESHOLD_SCENARIO_KEYS",
    "HEP_NEAR_THRESHOLD_SCENARIO_KEYS",
    "LinearStatisticDPSolver",
    "MCMCISResult",
    "MCMC_CHAINS",
    "MCMC_ESTIMATE_VARIANCE",
    "MCMC_IS_BETA_PILOT_SEED_OFFSET",
    "MCMC_IS_CHAIN_SEED_OFFSET",
    "MCMCIS_SWAP_FRACTIONS",
    "METHOD_BLOCKS",
    "NEAR_THRESHOLD_SCENARIO_KEYS",
    "N_BINS",
    "PermutationTestProblem",
    "SAMCResult",
    "SAMC_CHAIN_SEED_OFFSET",
    "SAMC_LAMBDA_MIN_PILOT",
    "SAMC_SETUP_SEED_OFFSET",
    "SAMC_SWAP_FRACTIONS",
    "Scenario",
    "T0",
    "TILT_MODE",
    "available_scenarios",
    "difference_in_means",
    "estimate_lambda_min",
    "estimate_scale_T",
    "hard_step_beta_for_target_tail_mass",
    "hard_step_r_for_target_tail_mass",
    "iid_pilot_statistics",
    "init_beta_from_iid_pilot",
    "job_seed",
    "load_scenario",
    "load_scenarios",
    "mcmc_is_chain_checkpoints",
    "method_block_index",
    "q_target_from_gamma",
    "run_hard_step_mcmc_is",
    "run_mcmc_is",
    "run_mcmc_is_checkpoints",
    "run_samc",
    "run_samc_checkpoints",
    "samc_chain_checkpoints",
    "treated_sum",
]
